include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    library_private_types_in_public_api: false
    use_build_context_synchronously: false
    depend_on_referenced_packages: false
    prefer_final_locals: true
    unnecessary_parenthesis: true
    implicit_call_tearoffs: true