name: fl_lib
description: "Flutter lib for common use cases."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  choice: ^2.3.2
  countly_flutter: ^24.4.0
  dio: ^5.4.2+1
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.22+1
  flutter_markdown_latex: ^0.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_auth: ^2.2.0
  logging: ^1.2.0
  markdown: ^7.2.2
  permission_handler: ^11.3.1
  share_plus: ^8.0.3
  url_launcher: ^6.2.6
  window_manager: ^0.3.8
  path_provider: ^2.1.3
  icloud_storage: ^2.2.0
  webdav_client:
    git:
      ref: main
      url: https://github.com/lollipopkit/webdav_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  generate: true
