name: fl_lib
description: "Flutter lib for common use cases."
version: 0.0.1
homepage: https://github.com/lppcg/fl_lib
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  choice: ^2.3.2
  crypto: ^3.0.3
  dio: ^5.4.2+1
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_markdown_latex: ^0.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  icloud_storage: ^2.2.0
  icons_plus: ^5.0.0
  intl: ^0.19.0
  local_auth: ^2.2.0
  logging: ^1.2.0
  markdown: ^7.2.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  shortid: ^0.1.2
  url_launcher: ^6.2.6
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  generate: true
